# Generated by Django 5.0.1 on 2024-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resume/')),
                ('portfolio', models.CharField(max_length=3000)),
                ('linkedin', models.CharField(max_length=3000)),
            ],
        ),
    ]
